const WORDPRESS_PREFIX = '@WORDPRESS';

export const CREATE_WORDPRESS = `${WORDPRESS_PREFIX}/CREATE_WORDPRESS`;
export const CREATE_WORDPRESS_SUCCESS = `${WORDPRESS_PREFIX}/CREATE_WORDPRESS_SUCCESS`;
export const CREATE_WORDPRESS_FAILURE = `${WORDPRESS_PREFIX}/CREATE_WORDPRESS_FAILURE`;

export const FETCH_WORDPRESS_DETAILS = `${WORDPRESS_PREFIX}/FETCH_WORDPRESS_DETAILS`;
export const FETCH_WORDPRESS_DETAILS_SUCCESS = `${WORDPRESS_PREFIX}/FETCH_WORDPRESS_DETAILS_SUCCESS`;
export const FETCH_WORDPRESS_DETAILS_FAILURE = `${WORDPRESS_PREFIX}/FETCH_WORDPRESS_DETAILS_FAILURE`;

export const DELETE_WORDPRESS = `${WORDPRESS_PREFIX}/DELETE_WORDPRESS`;
export const DELETE_WORDPRESS_SUCCESS = `${WORDPRESS_PREFIX}/DELETE_WORDPRESS_SUCCESS`;
export const DELETE_WORDPRESS_FAILURE = `${WORDPRESS_PREFIX}/DELETE_WORDPRESS_FAILURE`;

export const createWordpress = (data) => {
    return({
        type: CREATE_WORDPRESS,
        data:{data}
    })
}

export const fetchWordpressDetails = () =>{
    return ({
        type: FETCH_WORDPRESS_DETAILS
    })
}

export const deleteWordpress = (data) =>{
    return ({
        type: DELETE_WORDPRESS,
        data:{data}
    })
}